"""Generate the data-driven tables of the test plan as LaTeX ``tabular`` bodies.

    python scripts/make_plan_tables.py --out ../Project/tables

Each file holds only a ``tabular`` (booktabs rules); captions and labels stay
in the report text. The numbers come from the same YAML files the harness
runs on, so the plan and the code cannot drift apart.
"""

from __future__ import annotations

import argparse
from pathlib import Path

from flashrel.analysis.planning import USABLE_FRACTION, cycles_in, rotation_hours
from flashrel.config import Campaign, load_campaign
from flashrel.payload import fill_budget, plan_cycle
from flashrel.units import GiB, KiB, MiB

from planning_assumptions import NOMINAL, PESSIMISTIC, TEST_DAYS

REPO = Path(__file__).resolve().parents[1]
CLUSTER = 32 * KiB  # default exFAT allocation unit for 8 GB and 16 GB volumes


def _size(n: int) -> str:
    for unit, f in (("GiB", GiB), ("MiB", MiB), ("KiB", KiB)):
        if n >= f:
            v = n / f
            return f"{v:.0f}\\,{unit}" if v == int(v) else f"{v:.1f}\\,{unit}"
    return f"{n}\\,B"


def _thousands(n: float) -> str:
    return f"{n:,.0f}".replace(",", "{,}")


def drives_table(c: Campaign) -> str:
    one_host = len({a.host for a in c.assignments.values()}) == 1

    def place(drive_id: str) -> str:
        a = c.assignments[drive_id]
        return a.port if one_host else f"{a.host}/{a.port}"

    rows = []
    for code, group in c.inventory.groups.items():
        units = [u.drive_id for u in c.inventory.by_group(code) if u.drive_id in c.assignments]
        placed = ", ".join(f"{u}\\,({place(u)})" for u in units)
        rows.append(f"{code} & {group.brand} & {group.capacity_gb:g}\\,GB & {group.housing} & "
                    f"{group.listed_write.replace('MB/s', 'MB/s')} & "
                    f"\\${group.unit_price_usd:.2f} & {len(units)} \\\\\n"
                    f" & \\multicolumn{{6}}{{l}}{{\\scriptsize\\color{{black!60}} {placed}}} \\\\")
    body = "\n\\addlinespace[2pt]\n".join(rows)
    return ("\\begin{tabular}{@{}llllllr@{}}\n\\toprule\n"
            "Group & Brand & Capacity & Housing & Listed write & Price & $n$ \\\\\n\\midrule\n"
            f"{body}\n\\bottomrule\n\\end{{tabular}}\n")


def workloads_table(c: Campaign) -> str:
    rows = []
    for name in c.rotation:
        w = c.workloads[name]
        counts = []
        for cap in (8, 16):
            free = int(cap * 1e9 * USABLE_FRACTION)
            budget = fill_budget(free, c.cycle.fill_fraction, c.cycle.reserve_bytes)
            plan = plan_cycle(seed=c.seed, drive_id="TABLE", cycle=1, workload=w,
                              budget_bytes=budget, cluster_size=CLUSTER,
                              chunk_size=c.cycle.chunk_size)
            counts.append(_thousands(len(plan.files)))
        rows.append(f"{name.capitalize()} & {_size(w.min_size)}--{_size(w.max_size)} & "
                    f"{w.files_per_dir} & {counts[0]} & {counts[1]} \\\\")
    return ("\\begin{tabular}{@{}lcrrr@{}}\n\\toprule\n"
            " & File size & Files per & \\multicolumn{2}{c}{Files per cycle} \\\\\n"
            "\\cmidrule(l){4-5}\n"
            "Workload & (log-uniform) & folder & 8\\,GB & 16\\,GB \\\\\n\\midrule\n"
            + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n")


def feasibility_table(c: Campaign) -> str:
    rows = []
    for cap in (8, 16):
        payload = cap * 1e9 * USABLE_FRACTION * c.cycle.fill_fraction
        cells = [f"{cap}\\,GB", f"{payload / 1e9:.1f}"]
        for speeds in (NOMINAL, PESSIMISTIC):
            hours = rotation_hours(cap, speeds, fill_fraction=c.cycle.fill_fraction)
            n = cycles_in(TEST_DAYS, hours)
            cells += [f"{hours:.2f}", _thousands(n), f"{n * payload / 1e12:.1f}"]
        rows.append(" & ".join(cells) + " \\\\")
    return ("\\begin{tabular}{@{}lr rrr rrr@{}}\n\\toprule\n"
            " & Data per & \\multicolumn{3}{c}{Nominal speeds} & "
            "\\multicolumn{3}{c}{Write speeds halved} \\\\\n"
            "\\cmidrule(lr){3-5}\\cmidrule(l){6-8}\n"
            "Drive & cycle (GB) & h/cycle & cycles & TB & h/cycle & cycles & TB \\\\\n"
            "\\midrule\n" + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--config", default=str(REPO / "configs" / "campaign.yaml"))
    parser.add_argument("--out", default=str(REPO / "build" / "tables"))
    args = parser.parse_args()
    campaign = load_campaign(args.config)
    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)
    for name, build in (("tab_drives", drives_table), ("tab_workloads", workloads_table),
                        ("tab_feasibility", feasibility_table)):
        path = out / f"{name}.tex"
        path.write_text(f"% generated by Project_code/scripts/make_plan_tables.py; do not edit\n"
                        + build(campaign), encoding="utf-8")
        print(f"wrote {path}")


if __name__ == "__main__":
    main()
